# Learning: Pandas (3)

This jupyter notebook gives introduction to Python pandas package and its use in data science.

References:

Boris Paskhaver, Data Analysis with Pandas and Python, Udemy

The packages used in this notebook sheet are as follows. Notice that to import the packages, they must have been installed in the environment where this jupyter notebook is running.

In [22]:
import numpy as np
import pandas as pd

print("Numpy version: {}".format(np.__version__))
print("Panda version: {}".format(pd.__version__))

Numpy version: 1.23.5
Panda version: 1.5.2

The example data frames and series used in this notebook sheet are as follows. Notice that to read these csv files, they must have been downloaded to the same directory as this jupyter notebook.

The origin of these csv files can be found at Kaggle:
 - [Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon "https://www.kaggle.com/datasets/abcsds/pokemon")
 - [Google Stock Price](https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time "https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time")

## Data Frame

Pandas series introduced previously has a 1-dimensional data structure. By stacking series together, a 2-dimensional data structure, namely a data frame, can be obtained. Each column of a data frame can be taken as a series.

An example of a data frame is given below.

In [23]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

The above pokemon data frame is imported from a csv table without specifying index. Pandas has created a numeric incremenal index 0, 1, ..., 799 along each row in the table.

It is worth mentioning that **pandas assigns different types do each columns depending on the data it reads, and this might be affected if `NaN` presents in that column**. For example, an integer column with any `NaN` will be taken as a float column. The same applies to pandas series.

A data frame is a stack of multiple series. As introduced in an earlier notebook sheet, to abstract a column as a sereis from a data frame, use one of the following methods:
```python
series = dataframe.iloc[:,<column-index-number>]
series = dataframe['<column-name>']
series = dataframe[['<column-name>']].squeeze('columns')
```

Examples are given in earlier notebook sheet, thus are neglected here.

### Build/Update a Data Frame Shcema

A data frame schema here refers to its design of columns. It is usually built/updated by one of the following ways:
- Import a data frame from external.
- Build a data frame form series.
- Update a data frame by adding new columns to it, with either constant value or values derived from other information source.

**Build a data frame from series.**

The most commonly used way to create a data frame is to import from other source, such as from a csv file as introduced previously. It is possible though, to create a data frame from series using the following syntax.
```python
class pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)[source]

```

An example is given below.

In [24]:
index_s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
values_s = pd.Series([1, 1, 2, 3, 5, 8, 13, 21, 34, 55])
df_dict = {
    "F_Index": index_s,
    "F_Values": values_s
}
fibonacci = pd.DataFrame(df_dict)
fibonacci

   F_Index  F_Values
0        1         1
1        2         1
2        3         2
3        4         3
4        5         5
5        6         8
6        7        13
7        8        21
8        9        34
9       10        55

In [25]:
fibonacci = fibonacci.set_index("F_Index")
fibonacci

         F_Values
F_Index
1               1
2               1
3               2
4               3
5               5
6               8
7              13
8              21
9              34
10             55

**Modify data frame schema.**

Add a new column to an existing data frame as follows.
```python
<df>.insert(loc = <location>, column = "<new-column-name>", value = <value>)
```
and the new column will be the `<location>`-th column in the data frame, with the original `location`-th column is pushed to the right. The assigned `<value>` can be a constant scalar value or a series with approperate length.

Alternatively, simply use
```python
<df>["<new-column-name>"] = <value>
```
to append a new column to the right of the existing data frame. 

Examples are given below.

In [26]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df.insert(loc = 2, column = "In PokeDex", value = "Yes")
pokemon_df

,#,Name,In PokeDex,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Yes,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Yes,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Yes,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Yes,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Yes,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Yes,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Yes,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Yes,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Yes,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Yes,Fire,Water,600,80,110,120,130,90,70,6,True

In [27]:
pokemon_df["Favourite"] = "Yes"
pokemon_df

,#,Name,In PokeDex,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Favourite
0,1,Bulbasaur,Yes,Grass,Poison,318,45,49,49,65,65,45,1,False,Yes
1,2,Ivysaur,Yes,Grass,Poison,405,60,62,63,80,80,60,1,False,Yes
2,3,Venusaur,Yes,Grass,Poison,525,80,82,83,100,100,80,1,False,Yes
3,3,VenusaurMega Venusaur,Yes,Grass,Poison,625,80,100,123,122,120,80,1,False,Yes
4,4,Charmander,Yes,Fire,NaN,309,39,52,43,60,50,65,1,False,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Yes,Rock,Fairy,600,50,100,150,100,150,50,6,True,Yes
796,719,DiancieMega Diancie,Yes,Rock,Fairy,700,50,160,110,160,110,110,6,True,Yes
797,720,HoopaHoopa Confined,Yes,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Yes
798,720,HoopaHoopa Unbound,Yes,Psychic,Dark,680,80,160,60,170,130,80,6,True,Yes
799,721,Volcanion,Yes,Fire,Water,600,80,110,120,130,90,70,6,True,Yes

Add a new dynamic column to an existing data frame as follows. Here "dynamic" means that the content to be added in each row of this new column is not a constant, but depends on its the values in other columns. THis can be achieved by combining adding constant column with pandas series functions such as `.apply()` and `.map()`.

An example is given as follows. Consider adding a "Tier" column to the pokemon data frame. A tier of a pokemon is associated with its "Total" value.

In [28]:
pokemon_df = pd.read_csv('pokemon.csv')

def check_tier(total_sp):
    if total_sp >= 700:
        return "S+"
    elif total_sp >= 600:
        return "S"
    elif total_sp >= 500:
        return "A"
    elif total_sp >= 400:
        return "B"
    elif total_sp >= 300:
        return "C"
    else:
        return "D"

pokemon_df.insert(
    loc = 4,
    column = "Tier",
    value = pokemon_df["Total"].apply(check_tier)
)
pokemon_df

,#,Name,Type 1,Type 2,Tier,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,C,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,B,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,A,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,S,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,C,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,S,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,S+,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,S,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,S,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,S,600,80,110,120,130,90,70,6,True

### Commonly Used Data Frame Attributes and Methods

Pandas series and data frame share some common attributes and methods, and both of them have unique attributes and methods as well. Commonly used data frame attributes are summarized in the table below.

| Syntax | Description |
|:------ |:----------- |
| .size | The total length (column number multiplied by row number) of the data frame. |
| .shape | The shape (length in each dimension) of the data frame. |
| .values | The values of the data frame, in a 2D array. |
| .index | The row names of the data frame. |
| .columns | The column names given as an index object. |
| .axes | The `.index` combined with `.columns`. |
| .dtypes | The data type of each column of the data frame. |

Commonly used data frame methods are summarized in the table below.

| Syntax | Description |
|:------ |:----------- |
|.head(n=5)]), .tail(n=5)| Display the first and last rows in the data frame. |
| .info() | A summary of the data frame. |
| .count() | The number of no-NaN items in each column. |
| .sum(axis = 0) | Sum of all rows (axis 0) or columns (axis 1) and put the result in a series. |
| .value_counts() | Group the values in selected columns tuple and count the number in each group. |
| .insert() | Insert a column to the existing data frame. |
| .sort_values(by = None, ascending = True, inplace = False) | Sort the values by selected columns (the indices moves along with the values). |
| .sort_index(ascending = True, inplace = False) | Sort the index (the values move along with the indices). |
| .copy() | Ducplicate a series decoupled from its origin. |
| .get(\[ "\<column-name\>", ... \]) | Get a sub data frame of selected columns. |
| .dropna() | Remove rows with NaN. |
| .fillna() | Replace NaN with specified value. |

Notice that some of the attributes/methods share the same name and similar purpose between pandas series and data frame, but the returns can have different data structures and types.

### Access Items in Data Frame

To get a sub data frame from a data frame with selected columns, use either the `.get()` function, or use
```python
<df>[["<column-nam1>", ...]]
```

Examples are given below.

In [29]:
pokemon_df[["Name", "Type 1", "Type 2"]]

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [30]:
pokemon_df[["Name"]]

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[800 rows x 1 columns]

Notice that `<df>[["column-name"]]` returns a single-column data frame, while `<df>["column-name"]` returns a series. To convert the single-column data frame into a series, use the `.squeeze()` method. An example is given below.

In [31]:
pokemon_df[["Name"]].squeeze()

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

### Handling Missing Data

Notice that `NaN` is presented for column `Type 2` of some of the rows, which implies that the associated pokemon has only one type. In reality, a `NaN` in a dataset often means missing data. 

When that happens, the associated row usually needs to be handled specifically in one of the following ways:
- Remove the data with NaN.
- Replace NaN with meaningful data, either derived from other data source, or filled in with interpolation.
- Use a flag column to indicate missing data, and handle them specifically in later stage.

The same applies to pokemon data frame. If we want to analyze the secondary pokemon type of all pokemons, those without a secondary pokemon type rows need to be handled smartly.

**Consider removing the data with NaN.**

Drop rows with any NaN value as follows. More about `.dropna()` can be found [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html "https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html").
```python
<df> = <df>.dropna()
```
where notice that `<df>.dropna()` by iteslf does not modify the data frame.

Drop rows with all its column values NaN as follows.
```python
<df> = <df>.dropna(how = "all")
```

Drop rows whose selected columns values have NaN as follows.
```python
<df> = <df>.dropna(subset = ["column", ...])
```
in which case if any values with the selected columns is NaN, the row would be removed.

An example is given below.

In [32]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df.dropna()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [33]:
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [34]:
pokemon_df = pokemon_df.dropna()
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

**Consider replacing NaN with other data.**

Replace each and every NaN with a constant value as follows. More about `.fillna()` can be found [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html "https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html").
```python
<df> = <df>.fillna(<value>)
```
where notice that similar with `.dropna()`, the above does not modify the data frame.

Replace NaN in a specific column with a constant value as follows.
```python
<df>["<column-name>"] = <df>["<column-name>"].fillna(<value>)
```

In [35]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df[10:15]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False

In [36]:
pokemon_df = pokemon_df.fillna("Unknown")
pokemon_df[10:15]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,8,Wartortle,Water,Unknown,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,Unknown,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,Unknown,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,Unknown,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,Unknown,205,50,20,55,25,25,30,1,False

### ASTYPE method

Method `.astype()` can be used to convert data types of a data frame column. Make sure that the method is applied to non-NaN values, otherwide unexpected error may raise. The syntax is as follows.
```python
df["<column-name>"] = df["<column-name>"].astype("<new-type>")
```

Commonly seen data types in pandas are:

| Data Type | Description |
|:--------- |:----------- |
| int64 | 64-bit integer |
| int32 | 32-bit integer |
| float64 | 64-bit floating-point number |
| float32 | 32-bit floating-point number |
| object | String values |
| bool | Boolean values (True/False) |
| datetime64\[ns\] | Date and time values |
| category | Categorical variables |
| NaN | Missing or null values |


An example is given below.

In [53]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df["Attack"]

0       49
1       62
2       82
3      100
4       52
      ...
795    100
796    160
797    110
798    160
799    110
Name: Attack, Length: 800, dtype: int64

In [54]:
pokemon_df["Attack"] = pokemon_df["Attack"].astype("float")
pokemon_df["Attack"]

0       49.0
1       62.0
2       82.0
3      100.0
4       52.0
       ...
795    100.0
796    160.0
797    110.0
798    160.0
799    110.0
Name: Attack, Length: 800, dtype: float64

A category can be regarded as a data type of a column in a data frame. By correctly claiming a category column as category instead of object, the process, memory and storage load can be saved. This is especially effective when the unique value of a column is relatively small compared with the number of rows of the data frame.

An example is given below.

In [55]:
pokemon_df = pd.read_csv('pokemon.csv', index_col = "Name", usecols = ["Name", "Type 1", "Type 2", "Total"])
pokemon_df

                        Type 1  Type 2  Total
Name
Bulbasaur                Grass  Poison    318
Ivysaur                  Grass  Poison    405
Venusaur                 Grass  Poison    525
VenusaurMega Venusaur    Grass  Poison    625
Charmander                Fire     NaN    309
...                        ...     ...    ...
Diancie                   Rock   Fairy    600
DiancieMega Diancie       Rock   Fairy    700
HoopaHoopa Confined    Psychic   Ghost    600
HoopaHoopa Unbound     Psychic    Dark    680
Volcanion                 Fire   Water    600

[800 rows x 3 columns]

In [56]:
pokemon_df.info() # check memory usage

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, Bulbasaur to Volcanion
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Type 1  800 non-null    object
 1   Type 2  414 non-null    object
 2   Total   800 non-null    int64
dtypes: int64(1), object(2)
memory usage: 25.0+ KB

In [57]:
pokemon_df["Type 1"] = pokemon_df["Type 1"].astype("category")
pokemon_df.info() # check memory usage

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, Bulbasaur to Volcanion
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Type 1  800 non-null    category
 1   Type 2  414 non-null    object
 2   Total   800 non-null    int64
dtypes: category(1), int64(1), object(1)
memory usage: 20.2+ KB

### Sorting