# Learning: Pandas (1)

This jupyter notebook gives introduction to Python pandas package and its use in data science.

References:

Boris Paskhaver, Data Analysis with Pandas and Python, Udemy

The packages used in this notebook sheet are as follows. Notice that to import the packages, they must have been installed in the environment where this jupyter notebook is running.

In [1]:
import numpy as np
import pandas as pd

print("Numpy version: {}".format(np.__version__))
print("Panda version: {}".format(pd.__version__))

Numpy version: 1.23.5
Panda version: 1.5.2

## Data Importing

Pandas provides flexible data importing tools for variety of data resources types, including csv, excel, clipboard, json, html, xml, latex table, and many more. Details can be found [here](https://pandas.pydata.org/docs/reference/io.html "https://pandas.pydata.org/docs/reference/io.html").

In this notebook series, we mainly focus on importing data from csv files using `.read_csv()` method.

Pandas privede `.read_csv()` method that reads a csv file into a data frame. Its synax is given below. More details about `.read_csv()` are given [here](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html "https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html").
```python
pandas.read_csv(filepath_or_buffer, *, sep=_NoDefault.no_default, delimiter=None, header='infer', names=_NoDefault.no_default, index_col=None, usecols=None, squeeze=None, prefix=_NoDefault.no_default, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options=None)
```

More details about data frame is given in future notebook sheets.

Examples of using `.read_csv()` to import data is given below. 

In the first example, `pokemon.csv` from [here](https://www.kaggle.com/datasets/abcsds/pokemon "https://www.kaggle.com/datasets/abcsds/pokemon") is used as the data resource. It contains a table of many pokemons as well as their types and base parameters, as shown below.

In [2]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

It is possible to import selected columns only when using `.read_csv()`. An example is given below.

In [3]:
pokemon_lite_df = pd.read_csv('pokemon.csv', usecols = ['Name', 'Type 1', 'Type 2'])
pokemon_lite_df

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

It is possible to specify the a column to be used as the labels, instead of using increment labels 0, 1, 2, ... automatically generated by pandas. An example is given below.

In [4]:
pokemon_lite_df = pd.read_csv('pokemon.csv', index_col = 'Name', usecols = ['Name', 'Type 1', 'Type 2'])
pokemon_lite_df

                        Type 1  Type 2
Name
Bulbasaur                Grass  Poison
Ivysaur                  Grass  Poison
Venusaur                 Grass  Poison
VenusaurMega Venusaur    Grass  Poison
Charmander                Fire     NaN
...                        ...     ...
Diancie                   Rock   Fairy
DiancieMega Diancie       Rock   Fairy
HoopaHoopa Confined    Psychic   Ghost
HoopaHoopa Unbound     Psychic    Dark
Volcanion                 Fire   Water

[800 rows x 2 columns]

A pandas data frame is a stack of pandas series. Each column of the data frame is a pandas series. More details about pandas series is given in future notebook sheets.

A pandas series can be derived from a data frame as follows.

```python
series = dataframe.iloc[:,<column-index>]
series = dataframe['<column-name>']
series = dataframe[['<column-name>']].squeeze('columns')
```
where notice that `dataframe[['<column-name>']]` by itself is a single column data frame, not a series.

Examples are given below.

In [5]:
pokemon_name = pokemon_df.iloc[:,1]
pokemon_name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [6]:
pokemon_name = pokemon_df['Name']
pokemon_name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [7]:
pokemon_name = pokemon_df[['Name']].squeeze('columns')
pokemon_name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

It is possible to import a series from a csv file using `.read_csv()`, by combining the information above. An example is given below.

In [8]:
pokemon_name_series = pd.read_csv('pokemon.csv', usecols = ['Name']).squeeze('columns')
pokemon_name_series

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object