# Learning: Pandas (3)

This jupyter notebook gives introduction to Python pandas package and its use in data science.

References:

Boris Paskhaver, Data Analysis with Pandas and Python, Udemy

The packages used in this notebook sheet are as follows. Notice that to import the packages, they must have been installed in the environment where this jupyter notebook is running.

In [1]:
import numpy as np
import pandas as pd

print("Numpy version: {}".format(np.__version__))
print("Panda version: {}".format(pd.__version__))

Numpy version: 1.23.5
Panda version: 1.5.2

The example data frames and series used in this notebook sheet are as follows. Notice that to read these csv files, they must have been downloaded to the same directory as this jupyter notebook.

The origin of these csv files can be found at Kaggle:
 - [Pokemon](https://www.kaggle.com/datasets/abcsds/pokemon "https://www.kaggle.com/datasets/abcsds/pokemon")
 - [Google Stock Price](https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time "https://www.kaggle.com/datasets/akpmpr/google-stock-price-all-time")

In [2]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_series_name = pokemon_df['Name']
pokemon_series_name_type = pd.Series(data = list(pokemon_df['Type 1']), index = list(pokemon_df['Name']))
google_stock_df = pd.read_csv('google_stock.csv')
google_stock_price = google_stock_df['Adj Close']

## Data Frame

Pandas series introduced previously has a 1-dimensional data structure. By stacking series together, a 2-dimensional data structure, namely a data frame, can be obtained. Each column of a data frame can be taken as a series.

An example of a data frame is given below.

In [3]:
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

The above pokemon data frame is imported from a csv table without specifying index. Pandas has created a numeric incremenal index 0, 1, ..., 799 along each row in the table.

It is worth mentioning that **pandas assigns different types do each columns depending on the data it reads, and this might be affected if `NaN` presents in that column**. For example, an integer column with any `NaN` will be taken as a float column. The same applies to pandas series.

### Series and Data Frame Connections

A data frame is a stack of multiple series. As introduced in an earlier notebook sheet, to abstract a column as a sereis from a data frame, use one of the following methods:
```python
series = dataframe.iloc[:,<column-index-number>]
series = dataframe['<column-name>']
series = dataframe[['<column-name>']].squeeze('columns')
```

Examples are given in earlier notebook sheet, thus are neglected here.

### Build/Update a Data Frame

A data frame is usually built using one of the following ways:
- Import a data frame from external.
- Build a data frame from scratch or form series.
- Build a data frame on top of an existing data frame by adding new columns and rows.
- Build a data frame from existing data frame(s) by modifying or combining them together.

Add a new constant column to an existing data frame as follows.
```python
<df>.insert(loc = <location>, column = "<new-column-name>", value = <value>)
```
and the new column will be the `<location>`-th column in the data frame, with the original `location`-th column is pushed to the right.

Alternatively, simply use
```python
<df>["<new-column-name>"] = <value>
```
to append a new column to the right of the existing data frame. The assigned `<value>` can be a constant scalar value or a series with approperate length.

Examples are given below.

In [4]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df.insert(loc = 2, column = "In PokeDex", value = "Yes")
pokemon_df

,#,Name,In PokeDex,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Yes,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Yes,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Yes,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Yes,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Yes,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Yes,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Yes,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Yes,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Yes,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Yes,Fire,Water,600,80,110,120,130,90,70,6,True

In [5]:
pokemon_df["Favourite"] = "Yes"
pokemon_df

,#,Name,In PokeDex,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Favourite
0,1,Bulbasaur,Yes,Grass,Poison,318,45,49,49,65,65,45,1,False,Yes
1,2,Ivysaur,Yes,Grass,Poison,405,60,62,63,80,80,60,1,False,Yes
2,3,Venusaur,Yes,Grass,Poison,525,80,82,83,100,100,80,1,False,Yes
3,3,VenusaurMega Venusaur,Yes,Grass,Poison,625,80,100,123,122,120,80,1,False,Yes
4,4,Charmander,Yes,Fire,NaN,309,39,52,43,60,50,65,1,False,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Yes,Rock,Fairy,600,50,100,150,100,150,50,6,True,Yes
796,719,DiancieMega Diancie,Yes,Rock,Fairy,700,50,160,110,160,110,110,6,True,Yes
797,720,HoopaHoopa Confined,Yes,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Yes
798,720,HoopaHoopa Unbound,Yes,Psychic,Dark,680,80,160,60,170,130,80,6,True,Yes
799,721,Volcanion,Yes,Fire,Water,600,80,110,120,130,90,70,6,True,Yes

Add a new dynamic column to an existing data frame as follows. Here "dynamic" means that the content to be added in each row of this new column is not a constant, but depends on its the values in other columns. THis can be achieved by combining adding constant column with pandas series functions such as `.apply()` and `.map()`.

An example is given as follows. Consider adding a "Tier" column to the pokemon data frame. A tier of a pokemon is associated with its "Total" value.

In [6]:
pokemon_df = pd.read_csv('pokemon.csv')

def check_tier(total_sp):
    if total_sp >= 700:
        return "S+"
    elif total_sp >= 600:
        return "S"
    elif total_sp >= 500:
        return "A"
    elif total_sp >= 400:
        return "B"
    elif total_sp >= 300:
        return "C"
    else:
        return "D"

pokemon_df.insert(
    loc = 4,
    column = "Tier",
    value = pokemon_df["Total"].apply(check_tier)
)
pokemon_df

,#,Name,Type 1,Type 2,Tier,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,C,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,B,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,A,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,S,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,C,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,S,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,S+,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,S,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,S,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,S,600,80,110,120,130,90,70,6,True

### Handling Missing Data

Notice that `NaN` is presented for column `Type 2` of some of the rows, which implies that the associated pokemon has only one type. In reality, a `NaN` in a dataset often means missing data. 

When that happens, the associated row usually needs to be handled specifically in one of the following ways:
- Derive the missing data from other known data, if possible.
- Remove the entire row.
- Interpolate the missing data.
- Assign a special flag that says "this row contains a missing data", and handle carefully in later data processing stages.
- Do nothing, if it is safe to do so.

The same applies to pokemon data frame. If we want to analyze the secondary pokemon type of all pokemons, those without a secondary pokemon type rows need to be handled smartly.

Drop rows with any NaN value as follows.
```
<df> = <df>.dropna()
```
where notice that `<df>.dropna()` by iteslf does not modify the data frame.

Drop rows with all its column values NaN as follows.
```
<df> = <df>.dropna(how = "all")
```

Drop rows whose selected columns values have NaN as follows.
```
<df> = <df>.dropna(subset = ["column", ...])
```
in which case if any values with the selected columns is NaN, the row would be removed.

An example is given below.

In [7]:
pokemon_df = pd.read_csv('pokemon.csv')
pokemon_df.dropna()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [8]:
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [9]:
pokemon_df = pokemon_df.dropna()
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### Commonly Used Data Frame Attributes and Methods

Pandas series and data frame share some common attributes and methods, and both of them have unique attributes and methods as well. Commonly used data frame attributes are summarized in the table below.

| Syntax | Description |
|:------ |:----------- |
| .size | The total length (column number multiplied by row number) of the data frame. |
| .shape | The shape (length in each dimension) of the data frame. |
| .values | The values of the data frame, in a 2D array. |
| .index | The row names of the data frame. |
| .columns | The column names given as an index object. |
| .axes | The `.index` combined with `.columns`. |
| .dtypes | The data type of each column of the data frame. |

Commonly used data frame methods are summarized in the table below.

| Syntax | Description |
|:------ |:----------- |
|.head(n=5)]), .tail(n=5)| Display the first and last rows in the data frame. |
| .info() | A summary of the data frame. |
| .count() | The number of no-NaN items in each column. |
| .sum(axis = 0) | Sum of all rows (axis 0) or columns (axis 1) and put the result in a series. |
| .value_counts() | Group the values in selected columns tuple and count the number in each group. |
| .insert() | Insert a column to the existing data frame. |
| .sort_values(by = None, ascending = True, inplace = False) | Sort the values by selected columns (the indices moves along with the values). |
| .sort_index(ascending = True, inplace = False) | Sort the index (the values move along with the indices). |
| .copy() | Ducplicate a series decoupled from its origin. |
| .get(\[ "\<column-name\>", ... \]) | Get a sub data frame of selected columns. |

Notice that some of the attributes/methods share the same name and similar purpose between pandas series and data frame, but the returns can have different data structures and types.

### Access Items in Data Frame

To get a sub data frame from a data frame with selected columns, use either the `.get()` function, or use
```python
<df>[["<column-nam1>", ...]]
```

Examples are given below.

In [10]:
pokemon_df[["Name", "Type 1", "Type 2"]]

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
6                Charizard     Fire  Flying
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[414 rows x 3 columns]

In [11]:
pokemon_df[["Name"]]

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
6                Charizard
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[414 rows x 1 columns]

Notice that `<df>[["column-name"]]` returns a single-column data frame, while `<df>["column-name"]` returns a series. To convert the single-column data frame into a series, use the `.squeeze()` method. An example is given below.

In [12]:
pokemon_df[["Name"]].squeeze()

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
6                  Charizard
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 414, dtype: object