# Learning: Pandas (1)

This jupyter notebook gives introduction to Python pandas package and its use in data science.

References:

Boris Paskhaver, Data Analysis with Pandas and Python, Udemy

The packages used in this notebook are as follows. Notice that to import the packages, they must have been installed in the environment where this jupyter notebook is running.

In [1]:
import numpy as np
import pandas as pd

print("Numpy version: {}".format(np.__version__))
print("Panda version: {}".format(pd.__version__))

Numpy version: 1.23.5
Panda version: 1.5.2

## Series

Series is a data structure defined in pandas as follows. More details can be found [here](https://pandas.pydata.org/docs/reference/api/pandas.Series.html "https://pandas.pydata.org/docs/reference/api/pandas.Series.html").

```python
class pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
```

Pandas series is like a combination of Python list and dictionary: it traces items using both the preserved sequence and also the index.

### Build Series

Pandas series can be created from a Python list or a dictionary as follows.

```python
<series-name> = pd.Series(<values-list>, <index-list>)
<series-name> = pd.Series(<dictionary>)
```

Examples are given below.

In [2]:
s1 = pd.Series(["apple", "banana", "chocolate", "donut", "egg"], [1, 2, 3, 4, 5])
s1

1        apple
2       banana
3    chocolate
4        donut
5          egg
dtype: object

In [3]:
s2 = pd.Series(np.random.randn(5), ["a", "b", "c", "d", "e"])
s2

a    0.243440
b    0.522738
c   -0.200675
d   -0.365599
e   -0.188253
dtype: float64

From the above example, it is clear that the order of the original lists preserves.

The data type of the series depends on the values. Some commonly seen data types are `float64`, `int64`, `bool` and `object`. Items with different data types can be fixed in a list, in which case the series data type is likely to be identified as `object`. 

If no index is assigned, numeric index will be be used. An example is given below.

In [4]:
s3 = pd.Series(np.random.randn(10))
s3

0   -0.444869
1    0.075694
2    2.443563
3   -0.900902
4   -0.229416
5   -0.027747
6    1.567637
7   -0.816598
8    0.074042
9   -1.403182
dtype: float64

A series can also be created from a Python dictionary. A basic example is given below.

In [5]:
d4 = {
    1: "apple",
    2: "banana",
    3: "chocolate",
    4: "donut",
    5: "egg"
}
s4 = pd.Series(d4)
s4

1        apple
2       banana
3    chocolate
4        donut
5          egg
dtype: object

In [6]:
d5 = {
    "a": 2,
    "b": 3,
    "c": 5,
    "d": 7,
    "e": 11
}
s5 = pd.Series(d5)
s5

a     2
b     3
c     5
d     7
e    11
dtype: int64

One thing to notice here is that although in the above example, the pandas series looks like a Python dictionary, it indeed assigns hidden numeric orders to the items in the series, hence its order preserves. This makes a big difference between pandas series and Python dictionary.

Due to this reason, it is possible to assign multiple items with the same index in pandas series, which is impossible in Python dictionary.

### Series Methods and Attributes

Details of pandas series methods and attributes can be found [here](https://pandas.pydata.org/docs/reference/series.html "https://pandas.pydata.org/docs/reference/series.html"), some which are introduced as follows.

Commonly seen methods are listed as follows.

| Syntax | Description |
|:------ |:----------- |
| .count() | The number of items. |
| .sum() | Sum of all items. |
| .product() | Product of all items. |
| .mean() | Mean of all items. |
| .std() | Standard deviation of all items. |
| .median () | Median of all items. |
| .mode() | The mode of all items. |
| .min(), .max() | Min and max of all items. |
| .sort_values(ascending = True, inplace = False) | Sort the values (the indices moves along with the values). |
| .sort_index(ascending = True, inplace = False) | Sort the index (the values move along with the indices). |
| .get() | Get a particular item from the series using the index. |
| .copy() | Ducplicate a series decoupled from its origin. |
| .value_counts() | Group the values and count the number in each group. Useful when the values are of categories. |
| .apply() | Apply a function to each item in a series. |
| .map() | Map the value of each item in a series using an association. |

Notice that `<series>[index]` can also be used to get an item from the series using the index. While `.get()` returns `None` if the index does not in the series, `<series>[index]` raises an exception. It is also possible to specify what to return if the index does not exist when using `.get()`. More about `<series>[index]` will be introudced later.

Commonly seen attributes are aso follows.

| Syntax | Description |
|:------ |:----------- |
| .size | The length of the series. |
| .is_unique | A flag whether there is any duplication of values (not index) in the series. |
| .values | The values of the series, with adaptive data type. |
| .index | The index of the series, with adaptive data type. |
| .dtype | The data type of the values. |

Details are given as follows.

### Access Items in Series

Use `<series>.get(<index>)` to obtain the item of a series using the index. Alternatively, the items in a series can be accessed from its index as follows.
```python
<series>[index]
```
This allows not only get but also update the items in the series.


When numeric integer index is used in a series, it is possible to retrieve data batch. When non-numeric index is used in a series, it is possible to access the data via its hidden index 0, 1, 2, ... 

Examples are given below.

In [7]:
print("The first item: {}".format(s4[1]))
print("The fifth item: {}".format(s4[5]))
print(s4[[1, 2, 3, 4, 5]]) # return a series

The first item: apple
The fifth item: egg
1        apple
2       banana
3    chocolate
4        donut
5          egg
dtype: object

In [8]:
print(s4.loc[1:5]) # return batch data in a series
print(s4.loc[:3]) # return batch data in a series from first item
print(s4.loc[3:]) # return batch data in a series till last item

1        apple
2       banana
3    chocolate
4        donut
5          egg
dtype: object
1        apple
2       banana
3    chocolate
dtype: object
3    chocolate
4        donut
5          egg
dtype: object

In [9]:
print("The first item: {}".format(s5["a"]))
print("The fifth item: {}".format(s5["e"]))
print(s5[["a", "b", "c", "d", "e"]]) # return a series
print("The first item: {}".format(s5[0]))
print("The fifth item: {}".format(s5[4]))
print(s5[[0, 1, 2, 3, 4]]) # return a series

The first item: 2
The fifth item: 11
a     2
b     3
c     5
d     7
e    11
dtype: int64
The first item: 2
The fifth item: 11
a     2
b     3
c     5
d     7
e    11
dtype: int64

In [10]:
print(s4.loc[0:4]) # return batch data in a series
print(s4.loc[:2]) # return batch data in a series from first item
print(s4.loc[2:]) # return batch data in a series till last item

1        apple
2       banana
3    chocolate
4        donut
dtype: object
1     apple
2    banana
dtype: object
2       banana
3    chocolate
4        donut
5          egg
dtype: object

With `<series>[index]`, the value in the series can be updated by simply assigning a new value. An example is given below.

In [11]:
print(s4)
s4["5"] = "eggplant"
print(s4)

1        apple
2       banana
3    chocolate
4        donut
5          egg
dtype: object
1        apple
2       banana
3    chocolate
4        donut
5          egg
5     eggplant
dtype: object

If the index does not exist when assigning, a new item is appended to the series. An example is given below.

In [12]:
s4["6"] = "fries"
print(s4)

1        apple
2       banana
3    chocolate
4        donut
5          egg
5     eggplant
6        fries
dtype: object

### Copy of Series

By assigning a series to a new variable, the series is not duplicated. An example is shown below. Although the update is done via the copied series `s4_copy`, the original series `s4` is also affected by the update. 

This implies that similar with C/C++ and Python, the name of the array/list is nothing more than a memory address sharing of the same array/list. By using `=` to assign a new name for a series, the series is not duplicated in the memory.

In [13]:
s4 = pd.Series(d4) # reset s4 from d4
print("Original series: {}".format(s4[1]))
s4_view = s4 # not a true copy, but more than a view
print("Copied series: {}".format(s4_view[1]))
s4_view[1] = "avocado"
print("Copied series after update: {}".format(s4_view[1]))
print("Original series after change: {}".format(s4[1]))

Original series: apple
Copied series: apple
Copied series after update: avocado
Original series after change: avocado

To create a true copy, use `.copy()` function as shown in the following example. This creates an independent series decoupled from the original series.

In [14]:
s4 = pd.Series(d4) # reset s4 from d4
print("Original series: {}".format(s4[1]))
s4_copy = s4.copy() # true copy
print("Copied series: {}".format(s4_copy[1]))
s4_copy[1] = "avocado"
print("Copied series after update: {}".format(s4_copy[1]))
print("Original series after change: {}".format(s4[1]))

Original series: apple
Copied series: apple
Copied series after update: avocado
Original series after change: apple

Distinguishing view and copy is important. This is because some operations (especially writing operations) can only be applied to a copy, not a view. 

To illustrate this, an example using `pokemon.csv` is given below. More about `.read_csv()` will be introduced in the future. For now, just take it as a way of creating a data frame from an excel file. More about data frame will be introduced in later part of the notebook. For now, just think of it as a source of the series.

In [15]:
pokemon_single_column_df = pd.read_csv("pokemon.csv", usecols = ["Name"])
pokemon_series_view = pokemon_single_column_df.squeeze("columns") # a view
pokemon_series_view.sort_values() # this is okay
# pokemon_series_view.sort_values(inplace = True) # this will generate error

510                  Abomasnow
511    AbomasnowMega Abomasnow
68                        Abra
392                      Absol
393            AbsolMega Absol
                ...
632                    Zoroark
631                      Zorua
46                       Zubat
695                   Zweilous
794           Zygarde50% Forme
Name: Name, Length: 800, dtype: object

In [16]:
pokemon_series_view # the view is not modified

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

The reason
```python
pokemon_series_view.sort_values(inplace = True)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[29], line 4
      2 pokemon_series_view = pokemon_single_column_df.squeeze("columns") # a view
      3 pokemon_series_view.sort_values() # this is okay
----> 4 pokemon_series_view.sort_values(inplace = True)

File ~/miniconda3/envs/smart-home-dev/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~/miniconda3/envs/smart-home-dev/lib/python3.10/site-packages/pandas/core/series.py:3748, in Series.sort_values(self, axis, ascending, inplace, kind, na_position, ignore_index, key)
   3746 # GH 5856/5853
   3747 if inplace and self._is_cached:
-> 3748     raise ValueError(
   3749         "This Series is a view of some other array, to "
   3750         "sort in-place you must create a copy"
   3751     )
   3753 if is_list_like(ascending):
   3754     ascending = cast(Sequence[Union[bool, int]], ascending)

ValueError: This Series is a view of some other array, to sort in-place you must create a copy
```
would generate error is because `pokemon_series_view` is a view of the data frame `pokemon_single_column_df`. If inplace sorting is implemented to `pokemon_series_view`, pandas would be confused about what to do with its original data frame.

Instead of using inplace sorting, consider assigning the sorted values as follows.

In [17]:
pokemon_series_view = pokemon_series_view.sort_values() # this is okay
pokemon_series_view

510                  Abomasnow
511    AbomasnowMega Abomasnow
68                        Abra
392                      Absol
393            AbsolMega Absol
                ...
632                    Zoroark
631                      Zorua
46                       Zubat
695                   Zweilous
794           Zygarde50% Forme
Name: Name, Length: 800, dtype: object

In the above, `pokemon_series_view` is overwritten by the its sorted view. It is decoupled from the original data frame. As a result, pandas has no difficulty understand the code and carry out the sorting. As for the original data frame, it is not affected by the sorting, as shown below.

In [18]:
pokemon_single_column_df # the original data frame is not modified

                      Name
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
..                     ...
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion

[800 rows x 1 columns]

If in the very beginning, `.copy()` is used to create a copy, inplace sorting would have been possible, as shown below.

In [19]:
pokemon_series_copy = pokemon_single_column_df.squeeze("columns").copy() # a copy
pokemon_series_copy.sort_values(inplace = True)
pokemon_series_copy # the copy is modified

510                  Abomasnow
511    AbomasnowMega Abomasnow
68                        Abra
392                      Absol
393            AbsolMega Absol
                ...
632                    Zoroark
631                      Zorua
46                       Zubat
695                   Zweilous
794           Zygarde50% Forme
Name: Name, Length: 800, dtype: object

### Apply Method

The `.apply()` method applies a function to each item in a series. An example is given below.

In [20]:
pokemon_series = pd.read_csv("pokemon.csv", usecols = ["Name"]).squeeze("columns")
pokemon_series.apply(len)

0       9
1       7
2       8
3      21
4      10
       ..
795     7
796    19
797    19
798    18
799     9
Name: Name, Length: 800, dtype: int64

It is also possible to apply customized function using the `.apply()` method. An example is given below.

In [21]:
def is_long_name(pokemon_name):
    if len(pokemon_name) >= 10:
        return "long"
    elif len(pokemon_name) >= 8:
        return "middle"
    else:
        return "short"

In [22]:
pokemon_name_evaluation = pokemon_series.apply(is_long_name)
pokemon_name_evaluation

0      middle
1       short
2      middle
3        long
4        long
        ...
795     short
796      long
797      long
798      long
799    middle
Name: Name, Length: 800, dtype: object

### Map Method

The `.map()` function maps the values in a series using a given association (such as a dictionary, or a pandas series). An example is given below.

In [31]:
mappings = {
    "long" : "l",
    "middle": "m",
    "short": "s"
}

pokemon_name_evaluation.map(mappings)

0      m
1      s
2      m
3      l
4      l
      ..
795    s
796    l
797    l
798    l
799    m
Name: Name, Length: 800, dtype: object

If the mapping cannot be found in the association, a `NaN` will be returned for that item.

## Data Frame
TBA

## General Python Functions on Series and Data Frame

Commonly used methods defined by pandas series and data frame have been introduced previously. This part of the training focuses on general Python functions that can be applied on Series and Data Frame.

For demonstration purpose, import the following series and data frames from csv files as follows. More details about using `.read_csv()` function to import data is given in future learning materials.

In [24]:
pokemon_df = pd.read_csv("pokemon.csv")
pokemon_series = pd.read_csv("pokemon.csv", usecols = ["Name"]).squeeze("columns")

In [25]:
google_stock_df = pd.read_csv("google_stock.csv")
google_stock_series = pd.read_csv("google_stock.csv", usecols = ["Close"]).squeeze("columns")

### Head and Tail

Use `.head(<num>)` and `.tail(<num>)` functions to check the first and last few rows in the data frame or in the series. They give views of the original data frame or series. By defatult, 5 rows are displayed. Examples are given below.

In [26]:
pokemon_df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [27]:
pokemon_df.tail()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Python built-in functions such as `type()`, `len()`, `sorted()`, `list()`, `dict()`, `max()`, `min()` all apply to pandas series and data frames. Examples are given below.

### In

Use `in` to determine whether an item is included in the series or data frames as follows.
```python
<item> in <series>
<item> in <series>.index
<item> in <series>.values
```
Examples are given below.

In [28]:
pokemon_series

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [29]:
print(100 in pokemon_series)
print(100 in pokemon_series.index)
print("Mewtwo" in pokemon_series.values)

True
True
True